services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minio123}
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Консоль
    volumes:
      - minio-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-energy_db}
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      # Автоматическое выполнение скрипта создания таблиц
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    container_name: mlflow
    environment:
      MLFLOW_BACKEND_STORE_URI: postgresql://pguser:pgpass@postgres:5432/chestnykvt
      MLFLOW_ARTIFACT_ROOT: s3://mlflow/
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
    depends_on:
      minio:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    restart: unless-stopped

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-energy_db}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio123}
      MINIO_BUCKET: ${MINIO_BUCKET:-models}
      PYTHONPATH: /app:/
    ports:
      - "8003:8000"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    restart: unless-stopped

  # frontend:
  #   build: 
  #     context: ./app/frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow-scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://pguser:pgpass@postgres:5432/airflow
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - airflow-data:/opt/airflow
    command: >
      bash -c "airflow db migrate &&
               airflow scheduler"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://pguser:pgpass@postgres:5432/airflow
      AIRFLOW__WEBSERVER__WORKERS: 2
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - airflow-data:/opt/airflow
    command: bash -c "airflow webserver"
    ports:
      - "8080:8080"
    depends_on:
      airflow-scheduler:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pg-data:
  minio-data:
  airflow-data: