services:
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY:-minio123}
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Консоль
    volumes:
      - minio-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-energy_db}
      POSTGRES_MULTIPLE_DATABASES: "energy_db,airflow,mlflow"
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
      # Автоматическое выполнение скрипта создания таблиц
      - ./database:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.12.2
    container_name: mlflow
    entrypoint: >
      bash -c "
        pip install psycopg2-binary &&
        mlflow server --host 0.0.0.0 --backend-store-uri postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/mlflow --default-artifact-root s3://mlflow/
      "
    environment:
      MLFLOW_S3_ENDPOINT_URL: http://minio:9000
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY:-minio}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY:-minio123}
    depends_on:
      minio:
        condition: service_started
      postgres:
        condition: service_healthy
    ports:
      - "5000:5000"
    restart: unless-stopped

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-energy_db}
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minio}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minio123}
      MINIO_BUCKET: ${MINIO_BUCKET:-models}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      PYTHONPATH: /app:/
    ports:
      - "8003:8003"
    volumes:
      - ./logs:/app/logs
      - ./config:/app/config
      - ./.env:/app/.env
      - ./app/backend/api:/app/api
      - ./app/backend/main.py:/app/main.py
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_started
    restart: unless-stopped

  # frontend:
  #   build: 
  #     context: ./app/frontend
  #     dockerfile: Dockerfile
  #   container_name: frontend
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

  airflow-scheduler:
    image: apache/airflow:2.9.0
    container_name: airflow-scheduler
    user: "${AIRFLOW_UID:-50000}:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
      _AIRFLOW_DB_UPGRADE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    volumes:
      - ./app/backend/airflow/dags:/opt/airflow/dags
      - ./app/backend/airflow/logs:/opt/airflow/logs
      - ./app/backend/airflow/plugins:/opt/airflow/plugins
      - ./app/backend/airflow/config:/opt/airflow/config
    command: scheduler
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  airflow-webserver:
    image: apache/airflow:2.9.0
    container_name: airflow-webserver
    user: "${AIRFLOW_UID:-50000}:0"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true" 
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__WEBSERVER__WORKERS: 2
      AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
    volumes:
      - ./app/backend/airflow/dags:/opt/airflow/dags
      - ./app/backend/airflow/logs:/opt/airflow/logs
      - ./app/backend/airflow/plugins:/opt/airflow/plugins
      - ./app/backend/airflow/config:/opt/airflow/config
    command: webserver
    ports:
      - "8080:8080"
    depends_on:
      - airflow-scheduler
    restart: unless-stopped

volumes:
  pg-data:
  minio-data: